version: "3.3"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cuja
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
  mailcatcher:
    container_name: mailcatcher
    image: sj26/mailcatcher
    expose:
      - 1025
      - 1080
    ports:
      - 1025:1025
      - 1080:1080
volumes:
  my-db:
